/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hethongquanlykhachsan;

import java.sql.*;
import javax.swing.*;
public class FormDangKy extends javax.swing.JFrame {

     /**
      * Creates new form FormDangKy
      */
     public FormDangKy() {
          initComponents();
     }

     /**
      * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
      */
     @SuppressWarnings("unchecked")
     // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
     private void initComponents() {

          btThoat = new javax.swing.JButton();
          txtMayKhauMoi = new javax.swing.JTextField();
          jLabel1 = new javax.swing.JLabel();
          jLabel2 = new javax.swing.JLabel();
          txtTenDangNhap = new javax.swing.JTextField();
          jLabel3 = new javax.swing.JLabel();
          btDangKy = new javax.swing.JButton();
          txtGmail = new javax.swing.JTextField();
          jLabel4 = new javax.swing.JLabel();

          setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

          btThoat.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
          btThoat.setText("thoát");
          btThoat.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btThoatActionPerformed(evt);
               }
          });

          txtMayKhauMoi.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    txtMayKhauMoiActionPerformed(evt);
               }
          });

          jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
          jLabel1.setText("Tên dăng nhập");

          jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
          jLabel2.setText("Mật khẩu");

          txtTenDangNhap.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    txtTenDangNhapActionPerformed(evt);
               }
          });

          jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
          jLabel3.setText("ĐĂNG KÝ TÀI KHOẢN");

          btDangKy.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
          btDangKy.setText("Đăng ký");
          btDangKy.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btDangKyActionPerformed(evt);
               }
          });

          txtGmail.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    txtGmailActionPerformed(evt);
               }
          });

          jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
          jLabel4.setText("Gmail");

          javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
          getContentPane().setLayout(layout);
          layout.setHorizontalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(233, Short.MAX_VALUE)
                    .addComponent(jLabel3)
                    .addGap(294, 294, 294))
               .addGroup(layout.createSequentialGroup()
                    .addGap(92, 92, 92)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                         .addComponent(jLabel1)
                         .addComponent(jLabel2)
                         .addComponent(jLabel4))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                         .addComponent(txtGmail)
                         .addGroup(layout.createSequentialGroup()
                              .addComponent(btDangKy, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                              .addGap(63, 63, 63)
                              .addComponent(btThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                         .addComponent(txtTenDangNhap, javax.swing.GroupLayout.Alignment.LEADING)
                         .addComponent(txtMayKhauMoi, javax.swing.GroupLayout.Alignment.LEADING))
                    .addContainerGap(308, Short.MAX_VALUE))
          );
          layout.setVerticalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                    .addGap(38, 38, 38)
                    .addComponent(jLabel3)
                    .addGap(41, 41, 41)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                         .addComponent(jLabel1)
                         .addComponent(txtTenDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(48, 48, 48)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                         .addComponent(jLabel2)
                         .addComponent(txtMayKhauMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(txtGmail, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(jLabel4))
                    .addGap(29, 29, 29)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(btDangKy)
                         .addComponent(btThoat))
                    .addGap(72, 72, 72))
          );

          pack();
     }// </editor-fold>//GEN-END:initComponents

     private void btThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThoatActionPerformed
          // TODO add your handling code here:
          FormDangNhap frmDangNhap = new FormDangNhap();
          frmDangNhap.setLocationRelativeTo(this); // căn giữa màn hình
          frmDangNhap.setVisible(true);

    // Đóng form đăng ký hiện tại
          this.dispose();
     }//GEN-LAST:event_btThoatActionPerformed

     private void txtMayKhauMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMayKhauMoiActionPerformed
          // TODO add your handling code here:
     }//GEN-LAST:event_txtMayKhauMoiActionPerformed

     private void txtTenDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenDangNhapActionPerformed
          // TODO add your handling code here:
     }//GEN-LAST:event_txtTenDangNhapActionPerformed

     private void btDangKyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDangKyActionPerformed
           String user = txtTenDangNhap.getText().trim();
          String pass = txtMayKhauMoi.getText().trim();
          String gmail = txtGmail.getText().trim();

          // Kiểm tra dữ liệu trống
          if(user.isEmpty() || pass.isEmpty() || gmail.isEmpty()){
               JOptionPane.showMessageDialog(this, "Vui lòng điền đầy đủ thông tin!", "Thiếu thông tin", JOptionPane.WARNING_MESSAGE);
               return;
          }
          SqlConnect connHelper = new SqlConnect();
          String checkUserSql = "SELECT * FROM DangNhap WHERE USERNAME = ?";
          String insertSql = "INSERT INTO DangNhap(USERNAME, PASS, GMAIL) VALUES(?,?,?)";

          try(Connection con = connHelper.getConnection()) {
              // Kiểm tra user đã tồn tại chưa
               PreparedStatement pstCheck = con.prepareStatement(checkUserSql);
               pstCheck.setString(1, user);
               ResultSet rs = pstCheck.executeQuery();
               if(rs.next()){
                    JOptionPane.showMessageDialog(this, "Tên đăng nhập đã tồn tại!", "Lỗi", JOptionPane.WARNING_MESSAGE);
                    return;
               }
                   // Chèn user mới
               PreparedStatement pstInsert = con.prepareStatement(insertSql);
               pstInsert.setString(1, user);
               pstInsert.setString(2, pass);
               pstInsert.setString(3, gmail);
               int kq = pstInsert.executeUpdate();
               if(kq > 0){
                    JOptionPane.showMessageDialog(this, "Tạo tài khoản thành công!");
                    this.dispose(); // đóng form đăng ký
               }else{
                    JOptionPane.showMessageDialog(this, "Lỗi khi tạo tài khoản!", "Lỗi", JOptionPane.ERROR_MESSAGE);
               }

          } catch(Exception e){
               e.printStackTrace();
               JOptionPane.showMessageDialog(this, "Lỗi kết nối cơ sở dữ liệu: " + e.getMessage());
          }
     }//GEN-LAST:event_btDangKyActionPerformed

     private void txtGmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGmailActionPerformed
          // TODO add your handling code here:
     }//GEN-LAST:event_txtGmailActionPerformed

     /**
      * @param args the command line arguments
      */
     public static void main(String args[]) {
          /* Set the Nimbus look and feel */
          //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
          /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
           */
          try {
               for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("Nimbus".equals(info.getName())) {
                         javax.swing.UIManager.setLookAndFeel(info.getClassName());
                         break;
                    }
               }
          } catch (ClassNotFoundException ex) {
               java.util.logging.Logger.getLogger(FormDangKy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (InstantiationException ex) {
               java.util.logging.Logger.getLogger(FormDangKy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (IllegalAccessException ex) {
               java.util.logging.Logger.getLogger(FormDangKy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (javax.swing.UnsupportedLookAndFeelException ex) {
               java.util.logging.Logger.getLogger(FormDangKy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          }
          //</editor-fold>

          /* Create and display the form */
          java.awt.EventQueue.invokeLater(new Runnable() {
               public void run() {
                    new FormDangKy().setVisible(true);
               }
          });
     }

     // Variables declaration - do not modify//GEN-BEGIN:variables
     private javax.swing.JButton btDangKy;
     private javax.swing.JButton btThoat;
     private javax.swing.JLabel jLabel1;
     private javax.swing.JLabel jLabel2;
     private javax.swing.JLabel jLabel3;
     private javax.swing.JLabel jLabel4;
     private javax.swing.JTextField txtGmail;
     private javax.swing.JTextField txtMatKhau;
     private javax.swing.JTextField txtMatKhau1;
     private javax.swing.JTextField txtMayKhauMoi;
     private javax.swing.JTextField txtTenDangNhap;
     // End of variables declaration//GEN-END:variables
}
