/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hethongquanlykhachsan;

import java.sql.*;
import javax.swing.*;

public class FormDangNhap extends javax.swing.JFrame {

     private javax.swing.JButton btDangKy;
     private javax.swing.JButton btQuenMatKhau;

     public FormDangNhap() {
          initComponents();
          
     }

     /**
      * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
      */
     @SuppressWarnings("unchecked")
     // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
     private void initComponents() {

          jLabel1 = new javax.swing.JLabel();
          jLabel2 = new javax.swing.JLabel();
          txtTenDangNhap = new javax.swing.JTextField();
          jLabel3 = new javax.swing.JLabel();
          btDangNhap = new javax.swing.JButton();
          btThoat = new javax.swing.JButton();
          JMatKhau = new javax.swing.JPasswordField();
          btDangKyTK = new javax.swing.JButton();
          btDoiMatKhau = new javax.swing.JButton();

          setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
          setPreferredSize(new java.awt.Dimension(1000, 400));

          jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
          jLabel1.setText("Tên Đăng Nhập");

          jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
          jLabel2.setText("Mật Khẩu");

          txtTenDangNhap.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    txtTenDangNhapActionPerformed(evt);
               }
          });

          jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
          jLabel3.setText("HỆ THỐNG QUẢN LÝ KHÁNH SẠN");

          btDangNhap.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
          btDangNhap.setText("ĐĂNG NHẬP");
          btDangNhap.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btDangNhapActionPerformed(evt);
               }
          });

          btThoat.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
          btThoat.setText("THOÁT");
          btThoat.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btThoatActionPerformed(evt);
               }
          });

          JMatKhau.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    JMatKhauActionPerformed(evt);
               }
          });

          btDangKyTK.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
          btDangKyTK.setText("Tạo Tài Khoản");
          btDangKyTK.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btDangKyTKActionPerformed(evt);
               }
          });

          btDoiMatKhau.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
          btDoiMatKhau.setText("Quên Mật Khẩu");
          btDoiMatKhau.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btDoiMatKhauActionPerformed(evt);
               }
          });

          javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
          getContentPane().setLayout(layout);
          layout.setHorizontalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addGroup(layout.createSequentialGroup()
                              .addGap(203, 203, 203)
                              .addComponent(jLabel3))
                         .addGroup(layout.createSequentialGroup()
                              .addGap(92, 92, 92)
                              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                   .addComponent(jLabel1)
                                   .addComponent(jLabel2))
                              .addGap(18, 18, 18)
                              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                   .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                             .addComponent(btDangNhap)
                                             .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                                             .addComponent(btThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(txtTenDangNhap)
                                        .addComponent(JMatKhau))
                                   .addGroup(layout.createSequentialGroup()
                                        .addComponent(btDangKyTK)
                                        .addGap(33, 33, 33)
                                        .addComponent(btDoiMatKhau)))))
                    .addContainerGap(204, Short.MAX_VALUE))
          );
          layout.setVerticalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                    .addGap(45, 45, 45)
                    .addComponent(jLabel3)
                    .addGap(34, 34, 34)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                         .addComponent(jLabel1)
                         .addComponent(txtTenDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(48, 48, 48)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                         .addComponent(jLabel2)
                         .addComponent(JMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(72, 72, 72)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(btDangNhap)
                         .addComponent(btThoat))
                    .addGap(28, 28, 28)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(btDangKyTK)
                         .addComponent(btDoiMatKhau))
                    .addContainerGap(85, Short.MAX_VALUE))
          );

          pack();
     }// </editor-fold>//GEN-END:initComponents

     private void txtTenDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenDangNhapActionPerformed
          // TODO add your handling code here:
     }//GEN-LAST:event_txtTenDangNhapActionPerformed

     private void btDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDangNhapActionPerformed
          String user = txtTenDangNhap.getText().trim();
          String pass = new String(JMatKhau.getPassword());
          
          if(user.isEmpty() || pass.isEmpty()){
               JOptionPane.showMessageDialog(this, "Vui lòng nhập tên đăng nhập và mật khẩu!", "Thiếu thông tin", JOptionPane.WARNING_MESSAGE);
               return;
          }
          
          String sql = "SELECT * FROM DangNhap WHERE USERNAME = ? AND PASS = ?";
          SqlConnect connHelper = new SqlConnect();
          
          try (Connection con = connHelper.getConnection();
               PreparedStatement pst = con.prepareStatement(sql)) {

               pst.setString(1, user);
               pst.setString(2, pass);
               try (ResultSet rs = pst.executeQuery()) {
                    if (rs.next()) {
                         JOptionPane.showMessageDialog(this, "Đăng nhập thành công!");
                         FormMain frm = new FormMain();
                         frm.setLocationRelativeTo(this);
                         frm.setVisible(true);
                         this.dispose();
                    }else{
                         JOptionPane.showMessageDialog(this, "Sai username hoặc password!", "Đăng nhập thất bại", JOptionPane.WARNING_MESSAGE);
                    }
               }
          } catch (Exception e) {
               e.printStackTrace();
               JOptionPane.showMessageDialog(this, "Lỗi khi kết nối cơ sở dữ liệu: " + e.getMessage());
          }
     }//GEN-LAST:event_btDangNhapActionPerformed

     private void btThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThoatActionPerformed
          // TODO add your handling code here:
          System.exit(0);
     }//GEN-LAST:event_btThoatActionPerformed

     private void JMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMatKhauActionPerformed
          // TODO add your handling code here:
     }//GEN-LAST:event_JMatKhauActionPerformed

     private void btDangKyTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDangKyTKActionPerformed
          FormDangKy frmDangKy = new FormDangKy();
          frmDangKy.setLocationRelativeTo(this);
          frmDangKy.setVisible(true);
          this.setVisible(false);
     }//GEN-LAST:event_btDangKyTKActionPerformed

     private void btDoiMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDoiMatKhauActionPerformed
          FormQuenMatKhau frmQuenMatKhau = new FormQuenMatKhau();
          frmQuenMatKhau.setLocationRelativeTo(this);
          frmQuenMatKhau.setVisible(true);
          this.setVisible(false);
     }//GEN-LAST:event_btDoiMatKhauActionPerformed

     /**
      * @param args the command line arguments
      */
     public static void main(String args[]) {
          /* Set the Nimbus look and feel */
          //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
          /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
           */
          try {
               for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("Nimbus".equals(info.getName())) {
                         javax.swing.UIManager.setLookAndFeel(info.getClassName());
                         break;
                    }
               }
          } catch (ClassNotFoundException ex) {
               java.util.logging.Logger.getLogger(FormDangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (InstantiationException ex) {
               java.util.logging.Logger.getLogger(FormDangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (IllegalAccessException ex) {
               java.util.logging.Logger.getLogger(FormDangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (javax.swing.UnsupportedLookAndFeelException ex) {
               java.util.logging.Logger.getLogger(FormDangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          }
          //</editor-fold>

          /* Create and display the form */
          java.awt.EventQueue.invokeLater(new Runnable() {
               public void run(){
                    new FormDangNhap().setVisible(true);
               }
          });
     }

     // Variables declaration - do not modify//GEN-BEGIN:variables
     private javax.swing.JPasswordField JMatKhau;
     private javax.swing.JButton btDangKyTK;
     private javax.swing.JButton btDangNhap;
     private javax.swing.JButton btDoiMatKhau;
     private javax.swing.JButton btThoat;
     private javax.swing.JLabel jLabel1;
     private javax.swing.JLabel jLabel2;
     private javax.swing.JLabel jLabel3;
     private javax.swing.JTextField txtTenDangNhap;
     // End of variables declaration//GEN-END:variables
}
