/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hethongquanlykhachsan;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JTable;
public class FormDatPhong extends javax.swing.JFrame {

     /**
      * Creates new form FormDatPhong
      */
     DatPhongDao datPhongDao = new DatPhongDao();
     PhongDao phongDao = new PhongDao();
     
     public FormDatPhong() {
          initComponents();
          loadDatPhong();
     }
     
     private void loadDatPhong() {
          try {
              ResultSet rs = datPhongDao.getAllDatPhong();
              DefaultTableModel model = (DefaultTableModel) tblDatPhong.getModel();
              model.setRowCount(0); // xóa dữ liệu cũ
              while(rs.next()) {
                  model.addRow(new Object[]{
                      rs.getInt("MaDatPhong"),
                      rs.getInt("MaKH"),
                      rs.getInt("MaPhong"),
                      rs.getString("NgayDat"),
                      rs.getString("TrangThai"),
                      rs.getString("NgayNhan"),
                      rs.getString("NgayTra")
                  });
              }
          } catch(SQLException e) {
              JOptionPane.showMessageDialog(this, "Lỗi load dữ liệu: " + e.getMessage());
          }
      }
     /**
      * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
      */
     @SuppressWarnings("unchecked")
     // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
     private void initComponents() {

          jLabel7 = new javax.swing.JLabel();
          jLabel9 = new javax.swing.JLabel();
          txtMaDatPhong = new javax.swing.JTextField();
          txtMaKhachHang = new javax.swing.JTextField();
          jLayeredPane8 = new javax.swing.JLayeredPane();
          jLabel2 = new javax.swing.JLabel();
          txtNgayDat = new javax.swing.JTextField();
          jLabel3 = new javax.swing.JLabel();
          txtNgayNhan = new javax.swing.JTextField();
          jLabel4 = new javax.swing.JLabel();
          jLabel5 = new javax.swing.JLabel();
          jLabel6 = new javax.swing.JLabel();
          txtMaPhong = new javax.swing.JTextField();
          jScrollPane1 = new javax.swing.JScrollPane();
          tblDatPhong = new javax.swing.JTable();
          txtNgayTra = new javax.swing.JTextField();
          jLabel15 = new javax.swing.JLabel();
          cboTrangThai = new javax.swing.JComboBox<>();
          btXoaTrang = new javax.swing.JButton();
          btThemPhong = new javax.swing.JButton();
          btXoaPhong = new javax.swing.JButton();
          btSuaPhong = new javax.swing.JButton();
          btThoat = new javax.swing.JButton();

          setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

          jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
          jLabel7.setText("Ngày Nhận");

          jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
          jLabel9.setText("Trạng Thái");

          javax.swing.GroupLayout jLayeredPane8Layout = new javax.swing.GroupLayout(jLayeredPane8);
          jLayeredPane8.setLayout(jLayeredPane8Layout);
          jLayeredPane8Layout.setHorizontalGroup(
               jLayeredPane8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGap(0, 231, Short.MAX_VALUE)
          );
          jLayeredPane8Layout.setVerticalGroup(
               jLayeredPane8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGap(0, 55, Short.MAX_VALUE)
          );

          jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
          jLabel2.setText("Mã Đặt Phòng");

          jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
          jLabel3.setText("Mã Khách Hàng");

          jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
          jLabel4.setText("Mã Phòng");

          jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
          jLabel5.setText("Ngày Đặt");

          jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
          jLabel6.setText("Ngày Trả");

          tblDatPhong.setModel(new javax.swing.table.DefaultTableModel(
               new Object [][] {

               },
               new String [] {
                    "Mã Đặt Phòng", "Mã Khách Hàng", "Mã Phòng", "Ngày Đặt", "Trạng Thái", "Ngày Nhận", "Ngày Trả"
               }
          ));
          tblDatPhong.addMouseListener(new java.awt.event.MouseAdapter() {
               public void mouseClicked(java.awt.event.MouseEvent evt) {
                    tblDatPhongMouseClicked(evt);
               }
          });
          jScrollPane1.setViewportView(tblDatPhong);

          jLabel15.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
          jLabel15.setText("Quản Lý Đặt Phòng");

          cboTrangThai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Trống ", "Đã đặt" }));

          btXoaTrang.setText("Xóa Trắng");
          btXoaTrang.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btXoaTrangActionPerformed(evt);
               }
          });

          btThemPhong.setText("Thêm Phòng");
          btThemPhong.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btThemPhongActionPerformed(evt);
               }
          });

          btXoaPhong.setText("Xóa Phòng");
          btXoaPhong.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btXoaPhongActionPerformed(evt);
               }
          });

          btSuaPhong.setText("Sửa Phòng");
          btSuaPhong.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btSuaPhongActionPerformed(evt);
               }
          });

          btThoat.setText("Thoát");
          btThoat.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btThoatActionPerformed(evt);
               }
          });

          javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
          getContentPane().setLayout(layout);
          layout.setHorizontalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addGroup(layout.createSequentialGroup()
                              .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                   .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(61, 61, 61)
                                        .addComponent(cboTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                                   .addGroup(layout.createSequentialGroup()
                                        .addComponent(btXoaTrang, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(251, 251, 251))))
                         .addGroup(layout.createSequentialGroup()
                              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                   .addGroup(layout.createSequentialGroup()
                                        .addContainerGap(585, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                             .addComponent(jLabel7)
                                             .addComponent(jLabel6))
                                        .addGap(62, 62, 62))
                                   .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(btSuaPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(44, 44, 44)))
                              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                   .addComponent(btXoaPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                   .addComponent(txtNgayNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                   .addComponent(txtNgayTra, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                   .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(btThoat, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btThemPhong, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)))))
                    .addGap(123, 123, 123))
               .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addGroup(layout.createSequentialGroup()
                              .addGap(47, 47, 47)
                              .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 968, javax.swing.GroupLayout.PREFERRED_SIZE))
                         .addGroup(layout.createSequentialGroup()
                              .addGap(400, 400, 400)
                              .addComponent(jLabel15)))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                         .addGap(57, 57, 57)
                         .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                              .addComponent(jLayeredPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                   .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                             .addGroup(layout.createSequentialGroup()
                                                  .addComponent(jLabel2)
                                                  .addGap(38, 38, 38))
                                             .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                  .addComponent(jLabel3)
                                                  .addGap(37, 37, 37)))
                                        .addGroup(layout.createSequentialGroup()
                                             .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                  .addComponent(jLabel4)
                                                  .addComponent(jLabel5))
                                             .addGap(13, 13, 13)))
                                   .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                             .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                  .addComponent(txtMaPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                  .addComponent(txtMaKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                  .addComponent(txtNgayDat, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                                             .addGap(0, 0, Short.MAX_VALUE))
                                        .addComponent(txtMaDatPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))))
                         .addContainerGap(639, Short.MAX_VALUE)))
          );
          layout.setVerticalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                    .addGap(29, 29, 29)
                    .addComponent(jLabel15)
                    .addGap(31, 31, 31)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(cboTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(jLabel9))
                    .addGap(26, 26, 26)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(txtNgayNhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(jLabel7))
                    .addGap(26, 26, 26)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(txtNgayTra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(jLabel6))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(btSuaPhong)
                         .addComponent(btXoaPhong))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(btXoaTrang)
                         .addComponent(btThemPhong))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(btThoat)
                    .addGap(30, 30, 30)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(66, 66, 66))
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                         .addContainerGap()
                         .addComponent(jLayeredPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addGap(18, 18, 18)
                         .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                              .addComponent(jLabel2)
                              .addComponent(txtMaDatPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                         .addGap(28, 28, 28)
                         .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                              .addComponent(jLabel3)
                              .addComponent(txtMaKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                         .addGap(31, 31, 31)
                         .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                              .addComponent(jLabel4)
                              .addComponent(txtMaPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                         .addGap(27, 27, 27)
                         .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                              .addComponent(jLabel5)
                              .addComponent(txtNgayDat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                         .addContainerGap(617, Short.MAX_VALUE)))
          );

          pack();
     }// </editor-fold>//GEN-END:initComponents

     private void tblDatPhongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDatPhongMouseClicked
          int selectedRow = tblDatPhong.getSelectedRow();
          if(selectedRow >= 0) {
               DefaultTableModel model = (DefaultTableModel) tblDatPhong.getModel();
               txtMaDatPhong.setText(model.getValueAt(selectedRow, 0).toString());
               txtMaKhachHang.setText(model.getValueAt(selectedRow, 1).toString());
               txtMaPhong.setText(model.getValueAt(selectedRow, 2).toString());
               txtNgayDat.setText(model.getValueAt(selectedRow, 3).toString());
               cboTrangThai.setSelectedItem(model.getValueAt(selectedRow, 4).toString());
               txtNgayNhan.setText(model.getValueAt(selectedRow, 5).toString());
               txtNgayTra.setText(model.getValueAt(selectedRow, 6).toString());
          }
     }//GEN-LAST:event_tblDatPhongMouseClicked

     private void btXoaTrangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btXoaTrangActionPerformed
          txtMaDatPhong.setText("");
          txtMaKhachHang.setText("");
          txtMaPhong.setText("");
          txtNgayDat.setText("");
          txtNgayNhan.setText("");
          txtNgayTra.setText("");
          cboTrangThai.setSelectedIndex(0);
     }//GEN-LAST:event_btXoaTrangActionPerformed

     private void btThemPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThemPhongActionPerformed
          try {
               int maPhong = Integer.parseInt(txtMaPhong.getText());
               int maKH = Integer.parseInt(txtMaKhachHang.getText());
               String ngayDat = txtNgayDat.getText().trim();
               String trangThai = cboTrangThai.getSelectedItem().toString();

               if(datPhongDao.themDatPhong(maPhong, maKH, ngayDat, "", "", trangThai)) {
                    JOptionPane.showMessageDialog(this, "Đặt phòng thành công!");
                    phongDao.capNhatTrangThai(maPhong, "Đã đặt");
                    loadDatPhong();
                    btXoaTrangActionPerformed(null);
               }
          } catch(Exception e) {
               JOptionPane.showMessageDialog(this, "Lỗi: " + e.getMessage());
          }
     }//GEN-LAST:event_btThemPhongActionPerformed

     private void btXoaPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btXoaPhongActionPerformed
          try {
               int maDatPhong = Integer.parseInt(txtMaDatPhong.getText());
               int maPhong = Integer.parseInt(txtMaPhong.getText());

               int confirm = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn xóa?", "Xác nhận", JOptionPane.YES_NO_OPTION);
               if(confirm == JOptionPane.YES_OPTION) {
                   if(datPhongDao.xoaDatPhong(maDatPhong)) {
                       JOptionPane.showMessageDialog(this, "Xóa thành công!");
                       phongDao.capNhatTrangThai(maPhong, "Trống");
                       loadDatPhong();
                       btXoaTrangActionPerformed(null);
                   }
               }
           } catch(Exception e) {
               JOptionPane.showMessageDialog(this, "Lỗi: " + e.getMessage());
           }
     }//GEN-LAST:event_btXoaPhongActionPerformed

     private void btSuaPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSuaPhongActionPerformed
          try {
               int maDatPhong = Integer.parseInt(txtMaDatPhong.getText());
               int maPhong = Integer.parseInt(txtMaPhong.getText());
               int maKH = Integer.parseInt(txtMaKhachHang.getText());
               String ngayDat = txtNgayDat.getText().trim();
               String ngayNhan = txtNgayNhan.getText().trim();
               String ngayTra = txtNgayTra.getText().trim();
               String trangThai = cboTrangThai.getSelectedItem().toString();

               if(datPhongDao.suaDatPhong(maDatPhong, maPhong, maKH, ngayDat, ngayNhan, ngayTra, trangThai)) {
                   JOptionPane.showMessageDialog(this, "Cập nhật đặt phòng thành công!");
                   phongDao.capNhatTrangThai(maPhong, trangThai);
                   loadDatPhong();
                   btXoaTrangActionPerformed(null);
               }
           } catch(Exception e) {
               JOptionPane.showMessageDialog(this, "Lỗi: " + e.getMessage());
           }
     }//GEN-LAST:event_btSuaPhongActionPerformed

     private void btThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThoatActionPerformed
           dispose();
     }//GEN-LAST:event_btThoatActionPerformed

     /**
      * @param args the command line arguments
      */
     public static void main(String args[]) {
          /* Set the Nimbus look and feel */
          //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
          /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
           */
          try {
               for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("Nimbus".equals(info.getName())) {
                         javax.swing.UIManager.setLookAndFeel(info.getClassName());
                         break;
                    }
               }
          } catch (ClassNotFoundException ex) {
               java.util.logging.Logger.getLogger(FormDatPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (InstantiationException ex) {
               java.util.logging.Logger.getLogger(FormDatPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (IllegalAccessException ex) {
               java.util.logging.Logger.getLogger(FormDatPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (javax.swing.UnsupportedLookAndFeelException ex) {
               java.util.logging.Logger.getLogger(FormDatPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          }
          //</editor-fold>

          /* Create and display the form */
          java.awt.EventQueue.invokeLater(new Runnable() {
               public void run() {
                    new FormDatPhong().setVisible(true);
               }
          });
     }

     // Variables declaration - do not modify//GEN-BEGIN:variables
     private javax.swing.JButton btSuaPhong;
     private javax.swing.JButton btThemPhong;
     private javax.swing.JButton btThoat;
     private javax.swing.JButton btXoaPhong;
     private javax.swing.JButton btXoaTrang;
     private javax.swing.JComboBox<String> cboTrangThai;
     private javax.swing.JLabel jLabel15;
     private javax.swing.JLabel jLabel2;
     private javax.swing.JLabel jLabel3;
     private javax.swing.JLabel jLabel4;
     private javax.swing.JLabel jLabel5;
     private javax.swing.JLabel jLabel6;
     private javax.swing.JLabel jLabel7;
     private javax.swing.JLabel jLabel9;
     private javax.swing.JLayeredPane jLayeredPane8;
     private javax.swing.JScrollPane jScrollPane1;
     private javax.swing.JTable tblDatPhong;
     private javax.swing.JTextField txtMaDatPhong;
     private javax.swing.JTextField txtMaKhachHang;
     private javax.swing.JTextField txtMaPhong;
     private javax.swing.JTextField txtNgayDat;
     private javax.swing.JTextField txtNgayNhan;
     private javax.swing.JTextField txtNgayTra;
     // End of variables declaration//GEN-END:variables
}
