/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hethongquanlykhachsan;

import java.sql.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

public class FormHoaDon extends javax.swing.JFrame {
     
     HoaDonDao hoaDonDao = new HoaDonDao();
     /**
      * Creates new form FormHoaDon
      */
     public FormHoaDon() {
          initComponents();
          loadHoaDon();
     }

     private void loadHoaDon() {
          try {
               ResultSet rs = hoaDonDao.getAllHoaDon();
               DefaultTableModel model = (DefaultTableModel) tblHoaDon.getModel();
               model.setRowCount(0);
               while (rs.next()) {
                         model.addRow(new Object[]{
                         rs.getInt("MaHD"),
                         rs.getInt("MaKH"),
                         rs.getInt("MaPhong"),
                         rs.getString("NgayLap"),
                         rs.getDouble("TongTien")
                    });
               }
          } catch (Exception e) {
              JOptionPane.showMessageDialog(this, "Lỗi tải dữ liệu: " + e.getMessage());
          }
     }
     /**
      * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
      */
     @SuppressWarnings("unchecked")
     // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
     private void initComponents() {

          jLabel15 = new javax.swing.JLabel();
          jLabel2 = new javax.swing.JLabel();
          jLabel3 = new javax.swing.JLabel();
          jLabel4 = new javax.swing.JLabel();
          jLabel5 = new javax.swing.JLabel();
          txtMaHoaDon = new javax.swing.JTextField();
          txtMaDatPhong = new javax.swing.JTextField();
          txtTongTien = new javax.swing.JTextField();
          txtNgayLap = new javax.swing.JTextField();
          btXoaHoaDon = new javax.swing.JButton();
          btSuaHoaDon = new javax.swing.JButton();
          btThoat = new javax.swing.JButton();
          btXoaTrang = new javax.swing.JButton();
          btThemHoaDon = new javax.swing.JButton();
          jScrollPane1 = new javax.swing.JScrollPane();
          tblHoaDon = new javax.swing.JTable();
          jLabel6 = new javax.swing.JLabel();
          txtMaKH = new javax.swing.JTextField();

          setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

          jLabel15.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
          jLabel15.setText("Thông Tin Hóa Đơn");

          jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
          jLabel2.setText("Mã Hóa Đơn");

          jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
          jLabel3.setText("Mã Đặt Phòng");

          jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
          jLabel4.setText("Ngày Lập");

          jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
          jLabel5.setText("Tổng Tiền");

          btXoaHoaDon.setText("Xóa Hóa Đơn");
          btXoaHoaDon.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btXoaHoaDonActionPerformed(evt);
               }
          });

          btSuaHoaDon.setText("Sửa Hóa Đơn");
          btSuaHoaDon.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btSuaHoaDonActionPerformed(evt);
               }
          });

          btThoat.setText("Thoát");
          btThoat.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btThoatActionPerformed(evt);
               }
          });

          btXoaTrang.setText("Xóa Trắng");
          btXoaTrang.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btXoaTrangActionPerformed(evt);
               }
          });

          btThemHoaDon.setText("Thêm Hóa Đơn");
          btThemHoaDon.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btThemHoaDonActionPerformed(evt);
               }
          });

          tblHoaDon.setModel(new javax.swing.table.DefaultTableModel(
               new Object [][] {

               },
               new String [] {
                    "Mã Hóa ĐƠn", "Mã Khách Hàng", "Mã Đặt Phòng", "Ngày Lập", "Tổng TIền "
               }
          ));
          tblHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
               public void mouseClicked(java.awt.event.MouseEvent evt) {
                    tblHoaDonMouseClicked(evt);
               }
          });
          jScrollPane1.setViewportView(tblHoaDon);

          jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
          jLabel6.setText("Mã Khách Hàng");

          javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
          getContentPane().setLayout(layout);
          layout.setHorizontalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addGroup(layout.createSequentialGroup()
                              .addGap(420, 420, 420)
                              .addComponent(jLabel15))
                         .addGroup(layout.createSequentialGroup()
                              .addGap(161, 161, 161)
                              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                   .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                             .addComponent(jLabel3)
                                             .addComponent(jLabel4)
                                             .addComponent(jLabel2)
                                             .addComponent(jLabel5))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                             .addComponent(txtTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                             .addComponent(txtMaDatPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                             .addComponent(txtMaHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                             .addComponent(txtNgayLap, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                   .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtMaKH, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                              .addGap(107, 107, 107)
                              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                   .addComponent(btThemHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                   .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(btSuaHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btXoaHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btXoaTrang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 118, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 835, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(63, 63, 63))
          );
          layout.setVerticalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                    .addGap(66, 66, 66)
                    .addComponent(jLabel15)
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addGroup(layout.createSequentialGroup()
                              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                   .addComponent(jLabel2)
                                   .addComponent(txtMaHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                   .addComponent(jLabel6)
                                   .addComponent(txtMaKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                   .addComponent(jLabel3)
                                   .addComponent(txtMaDatPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                              .addGap(18, 18, 18)
                              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                   .addComponent(jLabel4)
                                   .addComponent(txtNgayLap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                              .addGap(18, 18, 18)
                              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                   .addComponent(txtTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                   .addComponent(jLabel5)))
                         .addGroup(layout.createSequentialGroup()
                              .addComponent(btThemHoaDon)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(btXoaHoaDon)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(btSuaHoaDon)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(btThoat)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(btXoaTrang)))
                    .addGap(18, 18, 18)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap())
          );

          pack();
     }// </editor-fold>//GEN-END:initComponents

     private void btXoaHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btXoaHoaDonActionPerformed
          try {
               int maHD = Integer.parseInt(txtMaHoaDon.getText());
               if (JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn xóa?", "Xác nhận", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                    if (hoaDonDao.xoaHoaDon(maHD)) {
                         JOptionPane.showMessageDialog(this, "Xóa hóa đơn thành công!");
                         loadHoaDon();
                         btXoaTrangActionPerformed(null);
                    }
               }
           } catch (Exception e) {
               JOptionPane.showMessageDialog(this, "Lỗi xóa: " + e.getMessage());
           }
     }//GEN-LAST:event_btXoaHoaDonActionPerformed

     private void btSuaHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSuaHoaDonActionPerformed
          try {
               int maHD = Integer.parseInt(txtMaHoaDon.getText());
               int maKH = Integer.parseInt(txtMaKH.getText());
               int maPhong = Integer.parseInt(txtMaDatPhong.getText());
               String ngayLap = txtNgayLap.getText().trim();
               double tongTien = Double.parseDouble(txtTongTien.getText());

               if (hoaDonDao.suaHoaDon(maHD, maKH, maPhong, ngayLap, tongTien)) {
                    JOptionPane.showMessageDialog(this, "Sửa hóa đơn thành công!");
                    loadHoaDon();
               }
          } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Lỗi sửa: " + e.getMessage());
          }
     }//GEN-LAST:event_btSuaHoaDonActionPerformed

     private void btThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThoatActionPerformed
          int confirm = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn thoát?", "Xác nhận thoát", JOptionPane.YES_NO_OPTION);
          if (confirm == JOptionPane.YES_OPTION) {
               dispose(); // Đóng cửa sổ hiện tại
          }
     }//GEN-LAST:event_btThoatActionPerformed

     private void btXoaTrangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btXoaTrangActionPerformed
          txtMaHoaDon.setText("");
          txtMaKH.setText("");
          txtMaDatPhong.setText("");
          txtNgayLap.setText("");
          txtTongTien.setText("");
     }//GEN-LAST:event_btXoaTrangActionPerformed

     private void btThemHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThemHoaDonActionPerformed
          try {
               int maKH = Integer.parseInt(txtMaKH.getText());
               int maPhong = Integer.parseInt(txtMaDatPhong.getText());
               String ngayLap = txtNgayLap.getText().trim();
               double tongTien = Double.parseDouble(txtTongTien.getText());

               if (hoaDonDao.themHoaDon(maKH, maPhong, ngayLap, tongTien)) {
                    JOptionPane.showMessageDialog(this, "Thêm hóa đơn thành công!");
                    loadHoaDon();
                    btXoaTrangActionPerformed(null);
               }
           } catch (Exception e) {
               JOptionPane.showMessageDialog(this, "Lỗi thêm: " + e.getMessage());
           }
     }//GEN-LAST:event_btThemHoaDonActionPerformed

     private void tblHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHoaDonMouseClicked
          int row = tblHoaDon.getSelectedRow();
          if (row >= 0) {
               txtMaHoaDon.setText(tblHoaDon.getValueAt(row, 0).toString());
               txtMaKH.setText(tblHoaDon.getValueAt(row, 1).toString());
               txtMaDatPhong.setText(tblHoaDon.getValueAt(row, 2).toString());
               txtNgayLap.setText(tblHoaDon.getValueAt(row, 3).toString());
               txtTongTien.setText(tblHoaDon.getValueAt(row, 4).toString());
          }
     }//GEN-LAST:event_tblHoaDonMouseClicked

     /**
      * @param args the command line arguments
      */
     public static void main(String args[]) {
          /* Set the Nimbus look and feel */
          //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
          /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
           */
          try {
               for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("Nimbus".equals(info.getName())) {
                         javax.swing.UIManager.setLookAndFeel(info.getClassName());
                         break;
                    }
               }
          } catch (ClassNotFoundException ex) {
               java.util.logging.Logger.getLogger(FormHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (InstantiationException ex) {
               java.util.logging.Logger.getLogger(FormHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (IllegalAccessException ex) {
               java.util.logging.Logger.getLogger(FormHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (javax.swing.UnsupportedLookAndFeelException ex) {
               java.util.logging.Logger.getLogger(FormHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          }
          //</editor-fold>

          /* Create and display the form */
          java.awt.EventQueue.invokeLater(new Runnable() {
               public void run() {
                    new FormHoaDon().setVisible(true);
               }
          });
     }

     // Variables declaration - do not modify//GEN-BEGIN:variables
     private javax.swing.JButton btSuaHoaDon;
     private javax.swing.JButton btThemHoaDon;
     private javax.swing.JButton btThoat;
     private javax.swing.JButton btXoaHoaDon;
     private javax.swing.JButton btXoaTrang;
     private javax.swing.JLabel jLabel15;
     private javax.swing.JLabel jLabel2;
     private javax.swing.JLabel jLabel3;
     private javax.swing.JLabel jLabel4;
     private javax.swing.JLabel jLabel5;
     private javax.swing.JLabel jLabel6;
     private javax.swing.JScrollPane jScrollPane1;
     private javax.swing.JTable tblHoaDon;
     private javax.swing.JTextField txtMaDatPhong;
     private javax.swing.JTextField txtMaHoaDon;
     private javax.swing.JTextField txtMaKH;
     private javax.swing.JTextField txtNgayLap;
     private javax.swing.JTextField txtTongTien;
     // End of variables declaration//GEN-END:variables
}
