/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hethongquanlykhachsan;

import java.sql.*;
import javax.swing.*;
public class FormQuenMatKhau extends javax.swing.JFrame {

     /**
      * Creates new form FormQuenMatKhau
      */
     public FormQuenMatKhau() {
          initComponents();
     }

     /**
      * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
      */
     @SuppressWarnings("unchecked")
     // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
     private void initComponents() {

          jLabel1 = new javax.swing.JLabel();
          jLabel2 = new javax.swing.JLabel();
          txtGmail = new javax.swing.JTextField();
          jLabel3 = new javax.swing.JLabel();
          btDoiMatKhau = new javax.swing.JButton();
          btThoat = new javax.swing.JButton();
          txtMayKhauMoi = new javax.swing.JTextField();

          setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

          jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
          jLabel1.setText("Gmail");

          jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
          jLabel2.setText("Mật khẩu mới");

          txtGmail.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    txtGmailActionPerformed(evt);
               }
          });

          jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
          jLabel3.setText("ĐỔI MẬT KHẨU");

          btDoiMatKhau.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
          btDoiMatKhau.setText("Đổi mật khẩu");
          btDoiMatKhau.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btDoiMatKhauActionPerformed(evt);
               }
          });

          btThoat.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
          btThoat.setText("thoát");
          btThoat.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btThoatActionPerformed(evt);
               }
          });

          txtMayKhauMoi.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    txtMayKhauMoiActionPerformed(evt);
               }
          });

          javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
          getContentPane().setLayout(layout);
          layout.setHorizontalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                    .addGap(92, 92, 92)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                         .addComponent(jLabel1)
                         .addComponent(jLabel2))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                         .addGroup(layout.createSequentialGroup()
                              .addComponent(btDoiMatKhau)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                              .addComponent(btThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                         .addComponent(txtGmail)
                         .addComponent(txtMayKhauMoi))
                    .addContainerGap(223, Short.MAX_VALUE))
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3)
                    .addGap(294, 294, 294))
          );
          layout.setVerticalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                    .addGap(38, 38, 38)
                    .addComponent(jLabel3)
                    .addGap(41, 41, 41)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                         .addComponent(jLabel1)
                         .addComponent(txtGmail, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(48, 48, 48)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                         .addComponent(jLabel2)
                         .addComponent(txtMayKhauMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(47, 47, 47)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(btDoiMatKhau)
                         .addComponent(btThoat))
                    .addContainerGap(82, Short.MAX_VALUE))
          );

          pack();
     }// </editor-fold>//GEN-END:initComponents

     private void txtGmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGmailActionPerformed
          // TODO add your handling code here:
     }//GEN-LAST:event_txtGmailActionPerformed

     private void btDoiMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDoiMatKhauActionPerformed
           String gmail = txtGmail.getText().trim();
        String passMoi = txtMayKhauMoi.getText().trim();

        if(gmail.isEmpty() || passMoi.isEmpty()){
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin!", "Thiếu thông tin", JOptionPane.WARNING_MESSAGE);
            return;
        }

        SqlConnect connHelper = new SqlConnect();
        String checkGmailSql = "SELECT * FROM DangNhap WHERE GMAIL = ?";
        String updateSql = "UPDATE DangNhap SET PASS = ? WHERE GMAIL = ?";

        try(Connection con = connHelper.getConnection()) {
            // Kiểm tra gmail tồn tại
            PreparedStatement pstCheck = con.prepareStatement(checkGmailSql);
            pstCheck.setString(1, gmail);
            ResultSet rs = pstCheck.executeQuery();
            if(!rs.next()){
                JOptionPane.showMessageDialog(this, "Gmail không tồn tại!", "Lỗi", JOptionPane.WARNING_MESSAGE);
                return;
            }

            // Cập nhật mật khẩu mới
            PreparedStatement pstUpdate = con.prepareStatement(updateSql);
            pstUpdate.setString(1, passMoi);
            pstUpdate.setString(2, gmail);
            int kq = pstUpdate.executeUpdate();
            if(kq > 0){
                JOptionPane.showMessageDialog(this, "Đổi mật khẩu thành công!");
                // Quay về form đăng nhập
                FormDangNhap frmDangNhap = new FormDangNhap();
                frmDangNhap.setLocationRelativeTo(this);
                frmDangNhap.setVisible(true);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Đổi mật khẩu thất bại!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            }

        } catch(Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi kết nối cơ sở dữ liệu: " + e.getMessage());
        }
     }//GEN-LAST:event_btDoiMatKhauActionPerformed

     private void btThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThoatActionPerformed
          // TODO add your handling code here:
          FormDangNhap frmDangNhap = new FormDangNhap();
          frmDangNhap.setLocationRelativeTo(this); // căn giữa màn hình
          frmDangNhap.setVisible(true);

    // Đóng form Quên mật khẩu hiện tại
          this.dispose();
     }//GEN-LAST:event_btThoatActionPerformed

     private void txtMayKhauMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMayKhauMoiActionPerformed
          // TODO add your handling code here:
     }//GEN-LAST:event_txtMayKhauMoiActionPerformed

     /**
      * @param args the command line arguments
      */
     public static void main(String args[]) {
          /* Set the Nimbus look and feel */
          //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
          /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
           */
          try {
               for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("Nimbus".equals(info.getName())) {
                         javax.swing.UIManager.setLookAndFeel(info.getClassName());
                         break;
                    }
               }
          } catch (ClassNotFoundException ex) {
               java.util.logging.Logger.getLogger(FormQuenMatKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (InstantiationException ex) {
               java.util.logging.Logger.getLogger(FormQuenMatKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (IllegalAccessException ex) {
               java.util.logging.Logger.getLogger(FormQuenMatKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (javax.swing.UnsupportedLookAndFeelException ex) {
               java.util.logging.Logger.getLogger(FormQuenMatKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          }
          //</editor-fold>

          /* Create and display the form */
          java.awt.EventQueue.invokeLater(new Runnable() {
               public void run() {
                    new FormQuenMatKhau().setVisible(true);
               }
          });
     }

     // Variables declaration - do not modify//GEN-BEGIN:variables
     private javax.swing.JButton btDoiMatKhau;
     private javax.swing.JButton btThoat;
     private javax.swing.JLabel jLabel1;
     private javax.swing.JLabel jLabel2;
     private javax.swing.JLabel jLabel3;
     private javax.swing.JTextField txtGmail;
     private javax.swing.JTextField txtMayKhauMoi;
     // End of variables declaration//GEN-END:variables
}
