/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hethongquanlykhachsan;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JTable;

public class FormQuanLyPhong extends javax.swing.JFrame {

     PhongDao dao = new PhongDao();
     boolean dangSua = false;

     
     public FormQuanLyPhong() {
          initComponents();
          loadPhong();
          dao.capNhatTenPhongChoAll();
     }
     
     private void loadPhong() {
          DefaultTableModel model = (DefaultTableModel) tblPhong.getModel();
          model.setRowCount(0);
          try {
                ResultSet rs = dao.getAllPhong();
                while (rs.next()) {
                    model.addRow(new Object[]{
                         rs.getInt("MaPhong"),
                         rs.getString("TenPhong"),
                         rs.getString("LoaiPhong"), // THÊM LOẠI PHÒNG
                         rs.getString("TrangThai")
                    });
               }
          } catch (SQLException e) {
               JOptionPane.showMessageDialog(this, "Lỗi tải dữ liệu: " + e.getMessage());
          }
    }
     /**
      * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
      */
     @SuppressWarnings("unchecked")
     // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
     private void initComponents() {

          btXoaTrang = new javax.swing.JButton();
          btThemPhong = new javax.swing.JButton();
          btXoaPhong = new javax.swing.JButton();
          txtMaPhong = new javax.swing.JTextField();
          btSuaPhong = new javax.swing.JButton();
          btThoat = new javax.swing.JButton();
          jLayeredPane8 = new javax.swing.JLayeredPane();
          jLabel2 = new javax.swing.JLabel();
          jLabel3 = new javax.swing.JLabel();
          jLabel4 = new javax.swing.JLabel();
          jScrollPane1 = new javax.swing.JScrollPane();
          tblPhong = new javax.swing.JTable();
          jLabel15 = new javax.swing.JLabel();
          cboTrangThai = new javax.swing.JComboBox<>();
          cboLoaiPhong = new javax.swing.JComboBox<>();
          txtTenPhong = new javax.swing.JTextField();
          jLabel5 = new javax.swing.JLabel();

          setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

          btXoaTrang.setText("Xóa Trắng");
          btXoaTrang.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btXoaTrangActionPerformed(evt);
               }
          });

          btThemPhong.setText("Thêm Phòng");
          btThemPhong.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btThemPhongActionPerformed(evt);
               }
          });

          btXoaPhong.setText("Xóa Phòng");
          btXoaPhong.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btXoaPhongActionPerformed(evt);
               }
          });

          btSuaPhong.setText("Sửa Phòng");
          btSuaPhong.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btSuaPhongActionPerformed(evt);
               }
          });

          btThoat.setText("Thoát");
          btThoat.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btThoatActionPerformed(evt);
               }
          });

          javax.swing.GroupLayout jLayeredPane8Layout = new javax.swing.GroupLayout(jLayeredPane8);
          jLayeredPane8.setLayout(jLayeredPane8Layout);
          jLayeredPane8Layout.setHorizontalGroup(
               jLayeredPane8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGap(0, 197, Short.MAX_VALUE)
          );
          jLayeredPane8Layout.setVerticalGroup(
               jLayeredPane8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGap(0, 55, Short.MAX_VALUE)
          );

          jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
          jLabel2.setText("Mã Phòng");

          jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
          jLabel3.setText("Tên Phòng");

          jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
          jLabel4.setText("Trạng Thái");

          tblPhong.setModel(new javax.swing.table.DefaultTableModel(
               new Object [][] {

               },
               new String [] {
                    "Mã Phòng", "Tên Phòng", "Loai Phong", "Trạng Thái"
               }
          ));
          tblPhong.addMouseListener(new java.awt.event.MouseAdapter() {
               public void mouseClicked(java.awt.event.MouseEvent evt) {
                    tblPhongMouseClicked(evt);
               }
          });
          jScrollPane1.setViewportView(tblPhong);

          jLabel15.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
          jLabel15.setText("Thông tin phòng");

          cboTrangThai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Trống ", "Đã Đặt", " " }));

          cboLoaiPhong.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Đơn ", "Đôi", " " }));

          jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
          jLabel5.setText("Loai Phong");

          javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
          getContentPane().setLayout(layout);
          layout.setHorizontalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                    .addGap(342, 342, 342)
                    .addComponent(jLabel15)
                    .addGap(0, 0, Short.MAX_VALUE))
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(53, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addComponent(jLabel4)
                         .addComponent(jLabel5))
                    .addGap(38, 38, 38)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addComponent(txtTenPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(cboTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(cboLoaiPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(101, 101, 101)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addComponent(btThemPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                              .addComponent(btSuaPhong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                              .addComponent(btXoaPhong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                              .addComponent(btXoaTrang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                              .addComponent(btThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(378, 378, 378))
               .addGroup(layout.createSequentialGroup()
                    .addGap(33, 33, 33)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 835, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                         .addGap(57, 57, 57)
                         .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                              .addComponent(jLayeredPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                   .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                             .addComponent(jLabel2)
                                             .addGap(44, 44, 44)
                                             .addComponent(txtMaPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                   .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 305, Short.MAX_VALUE)))
                         .addContainerGap(300, Short.MAX_VALUE)))
          );
          layout.setVerticalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                    .addGap(30, 30, 30)
                    .addComponent(jLabel15)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addGroup(layout.createSequentialGroup()
                              .addGap(82, 82, 82)
                              .addComponent(txtTenPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addGap(26, 26, 26)
                              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                   .addComponent(cboLoaiPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                   .addComponent(jLabel5))
                              .addGap(18, 18, 18)
                              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                   .addComponent(jLabel4)
                                   .addComponent(cboTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                         .addGroup(layout.createSequentialGroup()
                              .addGap(35, 35, 35)
                              .addComponent(btThemPhong)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(btXoaPhong)
                              .addGap(13, 13, 13)
                              .addComponent(btSuaPhong)
                              .addGap(13, 13, 13)
                              .addComponent(btThoat)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(btXoaTrang)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(83, 83, 83))
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                         .addContainerGap()
                         .addComponent(jLayeredPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addGap(18, 18, 18)
                         .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                              .addComponent(jLabel2)
                              .addComponent(txtMaPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                         .addGap(28, 28, 28)
                         .addComponent(jLabel3)
                         .addContainerGap(688, Short.MAX_VALUE)))
          );

          pack();
     }// </editor-fold>//GEN-END:initComponents

     private void btXoaTrangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btXoaTrangActionPerformed
          txtMaPhong.setText("");
          txtTenPhong.setText("");
          cboTrangThai.setSelectedIndex(0);
     }//GEN-LAST:event_btXoaTrangActionPerformed

     private void btThemPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThemPhongActionPerformed
          String loaiPhong = (String) cboLoaiPhong.getSelectedItem();
          String trangThai = (String) cboTrangThai.getSelectedItem();

          if (loaiPhong.isEmpty() || trangThai.isEmpty()) {
               JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin!");
               return;
          }
          try {
               // CHỈ CẦN LOẠI PHÒNG, TRIGGER SẼ TỰ TẠO TÊN PHÒNG
               if (dao.themPhong(loaiPhong)) {
                    JOptionPane.showMessageDialog(this, "Thêm phòng thành công!");
                    loadPhong();
                    btXoaTrangActionPerformed(null);
               }
          } catch (Exception e) {
               JOptionPane.showMessageDialog(this, "Lỗi thêm phòng: " + e.getMessage());
               e.printStackTrace();
          }
     }//GEN-LAST:event_btThemPhongActionPerformed

     private void btXoaPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btXoaPhongActionPerformed
          if (txtMaPhong.getText().isEmpty()) {
               JOptionPane.showMessageDialog(this, "Vui lòng chọn phòng cần xóa!");
               return;
          }
          int confirm = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn xóa phòng này?", "Xác nhận", JOptionPane.YES_NO_OPTION);
          if (confirm == JOptionPane.YES_OPTION) {
               try {
                    int maPhong = Integer.parseInt(txtMaPhong.getText());
                    if (dao.xoaPhong(maPhong)) {
                         JOptionPane.showMessageDialog(this, "Xóa thành công!");
                         loadPhong();
                         btXoaTrangActionPerformed(null);
                    }
               } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Lỗi xóa phòng: " + e.getMessage());
                    e.printStackTrace();
               }
          }
     }//GEN-LAST:event_btXoaPhongActionPerformed

     private void btSuaPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSuaPhongActionPerformed
          if (txtMaPhong.getText().isEmpty()) {
               JOptionPane.showMessageDialog(this, "Vui lòng chọn phòng cần sửa!");
               return;
          }
          try {
               int maPhong = Integer.parseInt(txtMaPhong.getText());
               String ten = txtTenPhong.getText().trim();
               String loaiPhong = (String) cboLoaiPhong.getSelectedItem();
               String trangThai = (String) cboTrangThai.getSelectedItem();

               if (ten.isEmpty() || loaiPhong.isEmpty() || trangThai.isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin!");
                    return;
               }

               if (dao.suaPhong(maPhong, ten, loaiPhong, trangThai)) {
                    JOptionPane.showMessageDialog(this, "Cập nhật thành công!");
                    loadPhong();
                    btXoaTrangActionPerformed(null);
               }
          } catch (Exception e) {
               JOptionPane.showMessageDialog(this, "Lỗi cập nhật phòng: " + e.getMessage());
               e.printStackTrace();
          }
     }//GEN-LAST:event_btSuaPhongActionPerformed

     private void btThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThoatActionPerformed
          int confirm = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn thoát?", "Xác nhận thoát", JOptionPane.YES_NO_OPTION);
          if (confirm == JOptionPane.YES_OPTION) {
               dispose(); // Đóng cửa sổ hiện tại
          }
     }//GEN-LAST:event_btThoatActionPerformed

     private void tblPhongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPhongMouseClicked
          try {
               int row = tblPhong.getSelectedRow();
               if (row >= 0) {
                    // XỬ LÝ NULL POINTER EXCEPTION
                    Object maPhongObj = tblPhong.getValueAt(row, 0);
                    Object tenPhongObj = tblPhong.getValueAt(row, 1);
                    Object loaiPhongObj = tblPhong.getValueAt(row, 2);
                    Object trangThaiObj = tblPhong.getValueAt(row, 3);
                    
                    if (maPhongObj != null) {
                         txtMaPhong.setText(maPhongObj.toString());
                    } else {
                         txtMaPhong.setText("");
                    }
                    
                    if (tenPhongObj != null) {
                         txtTenPhong.setText(tenPhongObj.toString());
                    } else {
                         txtTenPhong.setText("");
                    }
                    
                    if (loaiPhongObj != null) {
                         cboLoaiPhong.setSelectedItem(loaiPhongObj.toString());
                    } else {
                         cboLoaiPhong.setSelectedIndex(0);
                    }
                    
                    if (trangThaiObj != null) {
                         cboTrangThai.setSelectedItem(trangThaiObj.toString());
                    } else {
                         cboTrangThai.setSelectedIndex(0);
                    }
               }
          } catch (Exception e) {
               JOptionPane.showMessageDialog(this, "Lỗi khi chọn phòng: " + e.getMessage());
               e.printStackTrace();
          }
     }//GEN-LAST:event_tblPhongMouseClicked

     /**
      * @param args the command line arguments
      */
     public static void main(String args[]) {
          /* Set the Nimbus look and feel */
          //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
          /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
           */
          try {
               for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("Nimbus".equals(info.getName())) {
                         javax.swing.UIManager.setLookAndFeel(info.getClassName());
                         break;
                    }
               }
          } catch (ClassNotFoundException ex) {
               java.util.logging.Logger.getLogger(FormQuanLyPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (InstantiationException ex) {
               java.util.logging.Logger.getLogger(FormQuanLyPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (IllegalAccessException ex) {
               java.util.logging.Logger.getLogger(FormQuanLyPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (javax.swing.UnsupportedLookAndFeelException ex) {
               java.util.logging.Logger.getLogger(FormQuanLyPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          }
          //</editor-fold>
          //</editor-fold>

          /* Create and display the form */
          java.awt.EventQueue.invokeLater(new Runnable() {
               public void run() {
                    new FormQuanLyPhong().setVisible(true);
               }
          });
     }

     // Variables declaration - do not modify//GEN-BEGIN:variables
     private javax.swing.JButton btSuaPhong;
     private javax.swing.JButton btThemPhong;
     private javax.swing.JButton btThoat;
     private javax.swing.JButton btXoaPhong;
     private javax.swing.JButton btXoaTrang;
     private javax.swing.JComboBox<String> cboLoaiPhong;
     private javax.swing.JComboBox<String> cboTrangThai;
     private javax.swing.JLabel jLabel15;
     private javax.swing.JLabel jLabel2;
     private javax.swing.JLabel jLabel3;
     private javax.swing.JLabel jLabel4;
     private javax.swing.JLabel jLabel5;
     private javax.swing.JLayeredPane jLayeredPane8;
     private javax.swing.JScrollPane jScrollPane1;
     private javax.swing.JTable tblPhong;
     private javax.swing.JTextField txtMaPhong;
     private javax.swing.JTextField txtTenPhong;
     // End of variables declaration//GEN-END:variables
}
