/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hethongquanlykhachsan;

import java.sql.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

public class FormKhachHang extends javax.swing.JFrame {
     
     KhachHangDao khachHangDao = new KhachHangDao();
     /**
      * Creates new form FormKhachHang
      */
     public FormKhachHang() {
          initComponents();
          loadKhachHang();
     }

     private void loadKhachHang() {
          try {
               ResultSet rs = khachHangDao.getAllKhachHang();
               DefaultTableModel model = (DefaultTableModel) tblKhachHang.getModel();
               model.setRowCount(0);

               while (rs.next()) {
                    model.addRow(new Object[]{
                         rs.getInt("MaKH"),
                         rs.getString("TenKH"),
                         rs.getString("CMND"),
                         rs.getString("SDT"),
                         rs.getInt("Tuoi"),
                         rs.getInt("NamSinh"),
                         rs.getString("QueQuan"),
                         rs.getString("DiaChi")
                   });
               }
          } catch (Exception e) {
               JOptionPane.showMessageDialog(this, "Lỗi tải dữ liệu: " + e.getMessage());
          }
      }
     /**
      * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
      */
     @SuppressWarnings("unchecked")
     // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
     private void initComponents() {

          btthem = new javax.swing.JButton();
          jLabel9 = new javax.swing.JLabel();
          jButton2 = new javax.swing.JButton();
          txtmasv = new javax.swing.JTextField();
          jButton3 = new javax.swing.JButton();
          txttensv = new javax.swing.JTextField();
          btthoat = new javax.swing.JButton();
          jLayeredPane8 = new javax.swing.JLayeredPane();
          jLabel15 = new javax.swing.JLabel();
          txtquequan = new javax.swing.JTextField();
          jLabel2 = new javax.swing.JLabel();
          txtsdt = new javax.swing.JTextField();
          jLabel3 = new javax.swing.JLabel();
          txtnguoilienhe = new javax.swing.JTextField();
          jLabel4 = new javax.swing.JLabel();
          jLabel5 = new javax.swing.JLabel();
          txtdoituong = new javax.swing.JTextField();
          jLabel6 = new javax.swing.JLabel();
          jLabel7 = new javax.swing.JLabel();
          txtsdtnguoilienhe = new javax.swing.JTextField();
          btluu = new javax.swing.JButton();
          txtdiachi = new javax.swing.JTextField();
          jLabel16 = new javax.swing.JLabel();
          jScrollPane1 = new javax.swing.JScrollPane();
          tblSinhvien = new javax.swing.JTable();
          btxoatrang = new javax.swing.JButton();
          cbbmasv = new javax.swing.JComboBox<>();
          btThemKhachHang = new javax.swing.JButton();
          jLabel10 = new javax.swing.JLabel();
          btXoaKhachHang = new javax.swing.JButton();
          txtMaKH = new javax.swing.JTextField();
          btSuaKhachHang = new javax.swing.JButton();
          txtHoTen = new javax.swing.JTextField();
          btThoat = new javax.swing.JButton();
          jLayeredPane9 = new javax.swing.JLayeredPane();
          jLabel17 = new javax.swing.JLabel();
          txtCMND = new javax.swing.JTextField();
          jLabel8 = new javax.swing.JLabel();
          txtSDT = new javax.swing.JTextField();
          jLabel11 = new javax.swing.JLabel();
          txtNamSinh = new javax.swing.JTextField();
          jLabel12 = new javax.swing.JLabel();
          jLabel13 = new javax.swing.JLabel();
          txtTuoi = new javax.swing.JTextField();
          jLabel14 = new javax.swing.JLabel();
          jLabel18 = new javax.swing.JLabel();
          txtDiaChi = new javax.swing.JTextField();
          txtQueQuan = new javax.swing.JTextField();
          jLabel19 = new javax.swing.JLabel();
          jScrollPane2 = new javax.swing.JScrollPane();
          tblKhachHang = new javax.swing.JTable();
          btXoaTrang = new javax.swing.JButton();

          btthem.setText("them");
          btthem.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btthemActionPerformed(evt);
               }
          });

          jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
          jLabel9.setText("doi tuong");

          jButton2.setText("xoa");
          jButton2.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton2ActionPerformed(evt);
               }
          });

          jButton3.setText("sua");
          jButton3.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton3ActionPerformed(evt);
               }
          });

          btthoat.setText("thoat");
          btthoat.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btthoatActionPerformed(evt);
               }
          });

          jLabel15.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
          jLabel15.setText("Nhap thong tin sinh vien dai hoc chinh quy cua hutech");

          jLayeredPane8.setLayer(jLabel15, javax.swing.JLayeredPane.DEFAULT_LAYER);

          javax.swing.GroupLayout jLayeredPane8Layout = new javax.swing.GroupLayout(jLayeredPane8);
          jLayeredPane8.setLayout(jLayeredPane8Layout);
          jLayeredPane8Layout.setHorizontalGroup(
               jLayeredPane8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jLayeredPane8Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel15)
                    .addContainerGap())
          );
          jLayeredPane8Layout.setVerticalGroup(
               jLayeredPane8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jLayeredPane8Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel15)
                    .addContainerGap())
          );

          jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
          jLabel2.setText("ma sinh vien");

          jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
          jLabel3.setText("ten sinh vien");

          jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
          jLabel4.setText("que quan");

          jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
          jLabel5.setText("Sdt");

          jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
          jLabel6.setText("sdt nguoi lien he");

          jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
          jLabel7.setText("nguoi lien he");

          btluu.setText("luu");
          btluu.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btluuActionPerformed(evt);
               }
          });

          jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
          jLabel16.setText("dia chi");

          tblSinhvien.setModel(new javax.swing.table.DefaultTableModel(
               new Object [][] {

               },
               new String [] {
                    "STT", "Ma SV", "Ten SV", "Que Quan", "SDT", "Nguoi LH", "SDTNLH", "Doi Tuong", "Dia Chi"
               }
          ));
          tblSinhvien.addMouseListener(new java.awt.event.MouseAdapter() {
               public void mouseClicked(java.awt.event.MouseEvent evt) {
                    tblSinhvienMouseClicked(evt);
               }
          });
          jScrollPane1.setViewportView(tblSinhvien);

          btxoatrang.setText(" xoa trang");
          btxoatrang.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btxoatrangActionPerformed(evt);
               }
          });

          cbbmasv.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
          cbbmasv.addItemListener(new java.awt.event.ItemListener() {
               public void itemStateChanged(java.awt.event.ItemEvent evt) {
                    cbbmasvItemStateChanged(evt);
               }
          });

          setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

          btThemKhachHang.setText("Thêm Khách Hàng");
          btThemKhachHang.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btThemKhachHangActionPerformed(evt);
               }
          });

          jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
          jLabel10.setText("Quê Quán");

          btXoaKhachHang.setText("Xóa Khách Hàng");
          btXoaKhachHang.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btXoaKhachHangActionPerformed(evt);
               }
          });

          btSuaKhachHang.setText("Sửa Khách Hàng");
          btSuaKhachHang.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btSuaKhachHangActionPerformed(evt);
               }
          });

          btThoat.setText("Thoát");
          btThoat.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btThoatActionPerformed(evt);
               }
          });

          jLabel17.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
          jLabel17.setText("Danh Sách Khách Hàng");

          jLayeredPane9.setLayer(jLabel17, javax.swing.JLayeredPane.DEFAULT_LAYER);

          javax.swing.GroupLayout jLayeredPane9Layout = new javax.swing.GroupLayout(jLayeredPane9);
          jLayeredPane9.setLayout(jLayeredPane9Layout);
          jLayeredPane9Layout.setHorizontalGroup(
               jLayeredPane9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jLayeredPane9Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel17)
                    .addContainerGap())
          );
          jLayeredPane9Layout.setVerticalGroup(
               jLayeredPane9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jLayeredPane9Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel17)
                    .addContainerGap())
          );

          jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
          jLabel8.setText("Mã KH");

          jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
          jLabel11.setText("Họ Tên");

          jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
          jLabel12.setText("CMND");

          jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
          jLabel13.setText("Số Điện Thoại");

          jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
          jLabel14.setText("Năm sinh");

          jLabel18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
          jLabel18.setText("Tuổi ");

          jLabel19.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
          jLabel19.setText("Địa Chỉ");

          tblKhachHang.setModel(new javax.swing.table.DefaultTableModel(
               new Object [][] {

               },
               new String [] {
                    "Mã Khách Hàng", "Họ Tên", "CMND", "Số Điện Thoại", "Tuổi", "Quê Quán", "Năm Sinh", "Địa Chỉ"
               }
          ));
          tblKhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
               public void mouseClicked(java.awt.event.MouseEvent evt) {
                    tblKhachHangMouseClicked(evt);
               }
          });
          jScrollPane2.setViewportView(tblKhachHang);

          btXoaTrang.setText("Xóa Trắng");
          btXoaTrang.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btXoaTrangActionPerformed(evt);
               }
          });

          javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
          getContentPane().setLayout(layout);
          layout.setHorizontalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addGroup(layout.createSequentialGroup()
                              .addGap(327, 327, 327)
                              .addComponent(jLayeredPane9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                         .addGroup(layout.createSequentialGroup()
                              .addGap(25, 25, 25)
                              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                   .addComponent(jLabel8)
                                   .addComponent(jLabel12)
                                   .addComponent(jLabel13)
                                   .addComponent(jLabel11))
                              .addGap(30, 30, 30)
                              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                   .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                             .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                             .addComponent(txtMaKH, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtTuoi, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                                   .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                             .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                             .addComponent(txtCMND, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(80, 80, 80)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                             .addComponent(jLabel18)
                                             .addComponent(jLabel10)
                                             .addComponent(jLabel14)
                                             .addComponent(jLabel19))
                                        .addGap(29, 29, 29)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                             .addComponent(txtQueQuan, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                             .addComponent(txtNamSinh, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                             .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                   .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                             .addComponent(btXoaKhachHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                             .addComponent(btThemKhachHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                             .addComponent(btXoaTrang, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                             .addComponent(btSuaKhachHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                             .addComponent(btThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                         .addGroup(layout.createSequentialGroup()
                              .addContainerGap()
                              .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 968, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(27, Short.MAX_VALUE))
          );
          layout.setVerticalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(jLayeredPane9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jLabel8)
                         .addComponent(txtMaKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(jLabel18)
                         .addComponent(txtTuoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jLabel11)
                         .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(jLabel10)
                         .addComponent(txtQueQuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jLabel12)
                         .addComponent(txtCMND, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(jLabel14)
                         .addComponent(txtNamSinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jLabel13)
                         .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(jLabel19)
                         .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(20, 20, 20)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(btThemKhachHang)
                         .addComponent(btSuaKhachHang))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(btXoaKhachHang)
                         .addComponent(btThoat))
                    .addGap(23, 23, 23)
                    .addComponent(btXoaTrang)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(35, 35, 35))
          );

          pack();
     }// </editor-fold>//GEN-END:initComponents

     private void btthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btthemActionPerformed
         
     }//GEN-LAST:event_btthemActionPerformed

     private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
     }//GEN-LAST:event_jButton2ActionPerformed

     private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
     }//GEN-LAST:event_jButton3ActionPerformed

     private void btthoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btthoatActionPerformed

     }//GEN-LAST:event_btthoatActionPerformed

     private void btluuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btluuActionPerformed
       
     }//GEN-LAST:event_btluuActionPerformed

     private void tblSinhvienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSinhvienMouseClicked
         
     }//GEN-LAST:event_tblSinhvienMouseClicked

     private void btxoatrangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btxoatrangActionPerformed
       
     }//GEN-LAST:event_btxoatrangActionPerformed

     private void cbbmasvItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbbmasvItemStateChanged
       
     }//GEN-LAST:event_cbbmasvItemStateChanged

     private void btThemKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThemKhachHangActionPerformed
          try {
               String ten = txtHoTen.getText().trim();
               String cmnd = txtCMND.getText().trim();
               String sdt = txtSDT.getText().trim();
               int tuoi = Integer.parseInt(txtTuoi.getText().trim());
               int namSinh = Integer.parseInt(txtNamSinh.getText().trim());
               String queQuan = txtQueQuan.getText().trim();
               String diaChi = txtDiaChi.getText().trim();

               if (khachHangDao.themKhachHang(ten, cmnd, sdt, tuoi, namSinh, queQuan, diaChi)) {
                    JOptionPane.showMessageDialog(this, "Thêm khách hàng thành công!");
                    loadKhachHang();
                    btXoaTrangActionPerformed(null);
               }
          } catch (Exception e) {
               JOptionPane.showMessageDialog(this, "Lỗi thêm khách hàng: " + e.getMessage());
          }
     }//GEN-LAST:event_btThemKhachHangActionPerformed

     private void btXoaKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btXoaKhachHangActionPerformed
          try {
               int maKH = Integer.parseInt(txtMaKH.getText().trim());
               int confirm = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn xóa khách hàng này?", "Xác nhận", JOptionPane.YES_NO_OPTION);
               if (confirm == JOptionPane.YES_OPTION) {
                    if (khachHangDao.xoaKhachHang(maKH)) {
                         JOptionPane.showMessageDialog(this, "Xóa thành công!");
                         loadKhachHang();
                         btXoaTrangActionPerformed(null);
                    }
               }
          } catch (Exception e) {
               JOptionPane.showMessageDialog(this, "Lỗi xóa: " + e.getMessage());
          }
     }//GEN-LAST:event_btXoaKhachHangActionPerformed

     private void btSuaKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSuaKhachHangActionPerformed
          try {
               int maKH = Integer.parseInt(txtMaKH.getText().trim());
               String ten = txtHoTen.getText().trim();
               String cmnd = txtCMND.getText().trim();
               String sdt = txtSDT.getText().trim();
               int tuoi = Integer.parseInt(txtTuoi.getText().trim());
               int namSinh = Integer.parseInt(txtNamSinh.getText().trim());
               String queQuan = txtQueQuan.getText().trim();
               String diaChi = txtDiaChi.getText().trim();

               if (khachHangDao.suaKhachHang(maKH, ten, cmnd, sdt, tuoi, namSinh, queQuan, diaChi)) {
                    JOptionPane.showMessageDialog(this, "Cập nhật thông tin thành công!");
                    loadKhachHang();
               }
          } catch (Exception e) {
               JOptionPane.showMessageDialog(this, "Lỗi sửa: " + e.getMessage());
          }
     }//GEN-LAST:event_btSuaKhachHangActionPerformed

     private void btThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThoatActionPerformed
          dispose();
     }//GEN-LAST:event_btThoatActionPerformed

     private void tblKhachHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKhachHangMouseClicked
          int row = tblKhachHang.getSelectedRow();
          if (row >= 0) {
               txtMaKH.setText(tblKhachHang.getValueAt(row, 0).toString());
               txtHoTen.setText(tblKhachHang.getValueAt(row, 1).toString());
               txtCMND.setText(tblKhachHang.getValueAt(row, 2).toString());
               txtSDT.setText(tblKhachHang.getValueAt(row, 3).toString());
               txtTuoi.setText(tblKhachHang.getValueAt(row, 4).toString());
               txtNamSinh.setText(tblKhachHang.getValueAt(row, 5).toString());
               txtQueQuan.setText(tblKhachHang.getValueAt(row, 6).toString());
               txtDiaChi.setText(tblKhachHang.getValueAt(row, 7).toString());
          }
     }//GEN-LAST:event_tblKhachHangMouseClicked

     private void btXoaTrangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btXoaTrangActionPerformed
          txtMaKH.setText("");
          txtHoTen.setText("");
          txtCMND.setText("");
          txtSDT.setText("");
          txtTuoi.setText("");
          txtNamSinh.setText("");
          txtQueQuan.setText("");
          txtDiaChi.setText("");
     }//GEN-LAST:event_btXoaTrangActionPerformed

     /**
      * @param args the command line arguments
      */
     public static void main(String args[]) {
          /* Set the Nimbus look and feel */
          //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
          /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
           */
          try {
               for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("Nimbus".equals(info.getName())) {
                         javax.swing.UIManager.setLookAndFeel(info.getClassName());
                         break;
                    }
               }
          } catch (ClassNotFoundException ex) {
               java.util.logging.Logger.getLogger(FormKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (InstantiationException ex) {
               java.util.logging.Logger.getLogger(FormKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (IllegalAccessException ex) {
               java.util.logging.Logger.getLogger(FormKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (javax.swing.UnsupportedLookAndFeelException ex) {
               java.util.logging.Logger.getLogger(FormKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          }
          //</editor-fold>

          /* Create and display the form */
          java.awt.EventQueue.invokeLater(new Runnable() {
               public void run() {
                    new FormKhachHang().setVisible(true);
               }
          });
     }

     // Variables declaration - do not modify//GEN-BEGIN:variables
     private javax.swing.JButton btSuaKhachHang;
     private javax.swing.JButton btThemKhachHang;
     private javax.swing.JButton btThoat;
     private javax.swing.JButton btXoaKhachHang;
     private javax.swing.JButton btXoaTrang;
     private javax.swing.JButton btluu;
     private javax.swing.JButton btthem;
     private javax.swing.JButton btthoat;
     private javax.swing.JButton btxoatrang;
     private javax.swing.JComboBox<String> cbbmasv;
     private javax.swing.JButton jButton2;
     private javax.swing.JButton jButton3;
     private javax.swing.JLabel jLabel10;
     private javax.swing.JLabel jLabel11;
     private javax.swing.JLabel jLabel12;
     private javax.swing.JLabel jLabel13;
     private javax.swing.JLabel jLabel14;
     private javax.swing.JLabel jLabel15;
     private javax.swing.JLabel jLabel16;
     private javax.swing.JLabel jLabel17;
     private javax.swing.JLabel jLabel18;
     private javax.swing.JLabel jLabel19;
     private javax.swing.JLabel jLabel2;
     private javax.swing.JLabel jLabel3;
     private javax.swing.JLabel jLabel4;
     private javax.swing.JLabel jLabel5;
     private javax.swing.JLabel jLabel6;
     private javax.swing.JLabel jLabel7;
     private javax.swing.JLabel jLabel8;
     private javax.swing.JLabel jLabel9;
     private javax.swing.JLayeredPane jLayeredPane8;
     private javax.swing.JLayeredPane jLayeredPane9;
     private javax.swing.JScrollPane jScrollPane1;
     private javax.swing.JScrollPane jScrollPane2;
     private javax.swing.JTable tblKhachHang;
     private javax.swing.JTable tblSinhvien;
     private javax.swing.JTextField txtCMND;
     private javax.swing.JTextField txtDiaChi;
     private javax.swing.JTextField txtHoTen;
     private javax.swing.JTextField txtMaKH;
     private javax.swing.JTextField txtNamSinh;
     private javax.swing.JTextField txtQueQuan;
     private javax.swing.JTextField txtSDT;
     private javax.swing.JTextField txtTuoi;
     private javax.swing.JTextField txtdiachi;
     private javax.swing.JTextField txtdoituong;
     private javax.swing.JTextField txtmasv;
     private javax.swing.JTextField txtnguoilienhe;
     private javax.swing.JTextField txtquequan;
     private javax.swing.JTextField txtsdt;
     private javax.swing.JTextField txtsdtnguoilienhe;
     private javax.swing.JTextField txttensv;
     // End of variables declaration//GEN-END:variables
}
